CREATE TABLE CLITAB(CLIID INT NOT NULL, CLINM VARCHAR2(255));
ALTER TABLE CLITAB ADD PRIMARY KEY (CLIID);
CREATE SEQUENCE CLIID_SEQ START WITH 1 INCREMENT BY 1;
CREATE OR REPLACE TRIGGER CLIID_INS_TRG
BEFORE INSERT ON CLITAB FOR EACH ROW
BEGIN
  SELECT CLIID_SEQ.NEXTVAL INTO :NEW.CLIID FROM DUAL;
END;

